"""Un module fournit des constantes associées à chaque règle de vote."""

PLURALITY_SIMPLE = "PS"
PLURALITY_2_ROUNDS = "PR"
VETO = "VT"
BORDA = "BRD"
CONDORCET_SIMPLE = "CS"
CONDORCET_COPELAND = "CC"
CONDORCET_SIMPSON = "CSN"
EXHAUSTIVE_BALLOT = "EB"
APPROVAL = "AL"
